### PR TITLE
Add aliases to make the code more readable

### PR DESCRIPTION
**Pull request by mtanzi**

### CODE REVIEW

**Comment by hunterboerner** [comment]
LGTM. Thanks!

@mtanzi How'd you hear about this project?

**Comment by hunterboerner** [comment]
Oh, and if you want to help clean up other code, check out https://github.com/rabbit-ci/backend/pull/5.

**Comment by mtanzi** [comment]
Hi @hunterboerner I saw the link few days ago on slack and it looks very interesting! I believe Elixir/Erlang is a perfect ecosystem where to build a CI server :wink: 

Recently I have been looking around for a nice self hosted CI in order to be able to leave the `Jenkins` world, but so far I haven't found much. The only relevant project I saw (and trying at the moment) is [drone.io](https://github.com/drone), It works quite well even if is still young and a bit rough on the edges.

I'll definitely keep one eye on your project and help if I will be able to (I started with elixir not long ago so I am still in the steep and exciting learning curve :wink: )

**Comment by hunterboerner** [comment]
@mtanzi Drone doesn't support Windows or Mac :( That's why I'm making Rabbit CI

**Pull request merged**
